title: "Observability Lab Workshop"
description: "Technical hands-on workshop for Observability"
remote_theme: benc-uk/theme-msdark
hide_github: true
hide_tagline: true
favicon: https://github.com/observability-lab-cse/observability-lab-workshop/blob/b2cf13bf6b70b2e43522e92480b188e93baaa1f6/favicon.png
buttons:
  - b0:
    text: Workshop Index
    href: /observability-lab-workshop/