title: "Observability Lab Workshop"
description: "Technical hands-on workshop for Observability"
remote_theme: benc-uk/theme-msdark
hide_github: true
hide_tagline: true
favicon: ./favicon.png
buttons:
  - b0:
    text: Workshop Index
    href: observability-lab-workshop/